### ISSUE TITLE
Website not working?

### ISSUE THREAD

**Issue by saamerm** [snpptsdev/snppts#1]
Hey @jfversluis & @sthewissen 
I wasn't able to get to the website. Is it temporarily down, or are you guys shutting it down?

**Comment by jfversluis** [comment]
Hey! Thanks for using it!

The costs of the domain name didn't really outweigh what we got from it so we decided to shut it down. It still "runs" on http://snppts.azurewebsites.net/ but can't guarantee everything will work.

Sorry for that!

**Comment by saamerm** [comment]
I see, sad to see an awesome resource like that go away. Did you guys try to sell it to Microsoft yet? What would you need to resurrect it?

**Comment by sthewissen** [comment]
We've been looking into rebooting it one last time in a bit of a different format, stay tuned.
