### ISSUE TITLE
PR Submission Done, review is blocked?

### ISSUE THREAD

**Issue by fahadashiq12** [snpptsdev/snppts#146]
I have done a PR review done but review is blocked for some reason, I don't know about the reason what's the issue is anyone else have faced this issue?

**Comment by fahadashiq12** [comment]
Need to make live demo?

**Comment by IeuanWalker** [comment]
> I have done a PR review done but review is blocked for some reason, I don't know about the reason what's the issue is anyone else have faced this issue?

You just need to wait for the admin to review it

**Comment by jfversluis** [comment]
Yep, we need to review and merge the PR, we still want to see what is going in ;)
