### ISSUE TITLE
Website or project is abandoned ?

### ISSUE THREAD

**Issue by salesHgabriel** [snpptsdev/snppts#188]

**Comment by jfversluis** [comment]
Nope! We're here, submit your amazing designs!

**Comment by salesHgabriel** [comment]
Nice❤️, because I submitted and was approved, but not see on website 🥲

**Comment by jfversluis** [comment]
Oh then I have to check something 😄 will do tomorrow!

**Comment by salesHgabriel** [comment]
Tkss ❤️

**Comment by jfversluis** [comment]
Its added now! Thanks for letting me know!

**Comment by salesHgabriel** [comment]
You’re welcome 🤝

**Comment by MagicAndre1981** [comment]
dead again? 

`Error 403 - This web app is stopped.`

**Comment by jfversluis** [comment]
Dead again and for real this time. Check out this repo for the content!

**Comment by jfversluis** [comment]
More information: https://github.com/snpptsdev/snppts/issues/193
