### ISSUE TITLE
Add a property into the IAmASnippet for blog link

### ISSUE THREAD

**Issue by kphillpotts** [snpptsdev/snppts#19]
Quite a few entries into Snppts would link out to a blog post, would it be a good idea to have a dedicated field for this, so each entry doesn't have to munge in an `<a href=` tag into the description.

**Comment by sthewissen** [comment]
Agreed! Hacking in the anchor tag is a bit of a chore and error prone.

**Comment by sthewissen** [comment]
It's done!
