### ISSUE TITLE
A new method to add a snppt or author

### ISSUE THREAD

**Issue by alexandresanlim** [snpptsdev/snppts#78]
I've thinking...

Today sound bad add a new class away to add a new snppt or author,
why not create a .json archive for this?

See [this sample ](https://github.com/codyogden/killedbygoogle) from "killedbygoogle", when it's  added a new google death project, it's added in graveyard.json archive project. 

could create a snppts.json and authors.json

**Comment by jfversluis** [comment]
Thanks for the suggestion! I can see both pros and cons. Why is adding something to a json file different than adding a class?

I don’t think we will be changing this anytime soon though :)

**Comment by alexandresanlim** [comment]
@jfversluis 
I think:
- Performance to compile
- Facility to added a new
- A clean project

No problem man! i love this project and always think about how to improve ;)
but for now you will close it.

Tks.

**Comment by jfversluis** [comment]
We appreciate any and all input! So no worries at all! Please keep doing that :)

Thank you!
